Drop database employee;
CREATE DATABASE employee;
USE employee;
CREATE table employee(empno VARCHAR(20) NOT NULL PRIMARY KEY,emp_name VARCHAR(20) NOT NULL,dept VARCHAR(20) NOT NULL,salary INT NOT NULL,dob DATE NOT NULL,branch VARCHAR(20) NOT NULL);
DESCRIBE employee;
INSERT INTO employee (empno,emp_name,dept,salary,dob,branch) VALUES ('E101','Amit','Production',45000,'2000-03-12','Bangalore');
INSERT INTO employee (empno,emp_name,dept,salary,dob,branch) VALUES ('E102','Amit','HR',70000,'2002-07-03','Bangalore');
INSERT INTO employee (empno,emp_name,dept,salary,dob,branch) VALUES ('E103','sunita','Manager',120000,'2001-01-11','Mysore');
INSERT INTO employee (empno,emp_name,dept,salary,dob,branch) VALUES ('E104','sunita','IT',67000,'2001-08-01','Mysore');
INSERT INTO employee (empno,emp_name,dept,salary,dob,branch) VALUES ('E105','mahesh','Civil',145000,'2003-09-20','Mumbai');
SELECT * FROM employee;
SELECT empno,salary FROM employee;
SELECT avg(salary) FROM employee;
SELECT count(empno) FROM employee;
SELECT count(DISTINCT emp_name) FROM employee;
SELECT sum(salary),emp_name,count(emp_name) FROM employee GROUP BY emp_name HAVING COUNT(emp_name)>1;
SELECT * FROM employee WHERE salary>120000;
SELECT emp_name FROM employee ORDER BY emp_name desc;
SELECT * FROM employee WHERE emp_name="Amit" AND salary>50000;
TRUNCATE employee;
